In [1]:
import pandas as pd
from langdetect import detect

In [2]:
reviews = pd.read_csv("apify_all_reviews.csv")
reviews

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/40,reviewImageUrls/41,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49
0,88 Seafood,4,"First time dinning here, tze char is just Infr...",2024-02-13T13:24:58.483Z,0,J Dotz,7.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,88 Seafood,5,This was my first time eating here. I can tell...,2023-12-25T02:14:33.909Z,0,judy ng,18.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,88 Seafood,4,Considering that the dining area is next to a ...,2024-01-09T15:06:22.201Z,0,Veronica Pestana,141.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,88 Seafood,4,1st time came was 5 months ago. A decent Cze C...,2023-10-29T10:48:53.638Z,0,Clo’s Laobu,68.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,88 Seafood,5,"First time experiencing prawning, we spend a g...",2023-08-08T05:02:23.357Z,0,Loh Soon Shan,120.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,Fu Zhen Seafood Restaurant,3,Affordable ZiChar stall located in a coffeesho...,2022-06-19T07:37:43.038Z,0,Bastian Lew,29.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10889,Fu Zhen Seafood Restaurant,4,"Beef hor fan thick gravy , savoury with beef s...",2022-05-23T04:59:31.966Z,1,Kelvin Teo,87.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10890,Fu Zhen Seafood Restaurant,4,"Ordered chicken fried rice with 2 extra eggs, ...",2021-09-28T09:52:23.269Z,0,Sihan Goi,247.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10891,Fu Zhen Seafood Restaurant,2,Not ordering from these guys again.\n\nGarlic ...,2022-09-19T11:36:43.707Z,0,Jeffrey “jf” Lim,78.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10892,Fu Zhen Seafood Restaurant,3,Egg was tasty but oysters not good,2022-10-27T12:24:29.650Z,0,MrHoopies,145.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# drop reviews that do not contain any test or did not rate any stars
reviews.drop(reviews[(reviews.text.isnull()) | (reviews.stars.isnull())].index, inplace=True)
reviews

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/40,reviewImageUrls/41,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49
0,88 Seafood,4,"First time dinning here, tze char is just Infr...",2024-02-13T13:24:58.483Z,0,J Dotz,7.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,88 Seafood,5,This was my first time eating here. I can tell...,2023-12-25T02:14:33.909Z,0,judy ng,18.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,88 Seafood,4,Considering that the dining area is next to a ...,2024-01-09T15:06:22.201Z,0,Veronica Pestana,141.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,88 Seafood,4,1st time came was 5 months ago. A decent Cze C...,2023-10-29T10:48:53.638Z,0,Clo’s Laobu,68.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,88 Seafood,5,"First time experiencing prawning, we spend a g...",2023-08-08T05:02:23.357Z,0,Loh Soon Shan,120.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,Fu Zhen Seafood Restaurant,3,Affordable ZiChar stall located in a coffeesho...,2022-06-19T07:37:43.038Z,0,Bastian Lew,29.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10889,Fu Zhen Seafood Restaurant,4,"Beef hor fan thick gravy , savoury with beef s...",2022-05-23T04:59:31.966Z,1,Kelvin Teo,87.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10890,Fu Zhen Seafood Restaurant,4,"Ordered chicken fried rice with 2 extra eggs, ...",2021-09-28T09:52:23.269Z,0,Sihan Goi,247.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10891,Fu Zhen Seafood Restaurant,2,Not ordering from these guys again.\n\nGarlic ...,2022-09-19T11:36:43.707Z,0,Jeffrey “jf” Lim,78.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10892,Fu Zhen Seafood Restaurant,3,Egg was tasty but oysters not good,2022-10-27T12:24:29.650Z,0,MrHoopies,145.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
def check_en(row):
    '''
    check if the review text is in English or not
    '''
    try:
        lang = detect(row['text'])
    except:
        lang = 'NA'
    return lang 
reviews["lang"] = reviews.apply(check_en, axis=1)
reviews

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/41,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang
0,88 Seafood,4,"First time dinning here, tze char is just Infr...",2024-02-13T13:24:58.483Z,0,J Dotz,7.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
1,88 Seafood,5,This was my first time eating here. I can tell...,2023-12-25T02:14:33.909Z,0,judy ng,18.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
2,88 Seafood,4,Considering that the dining area is next to a ...,2024-01-09T15:06:22.201Z,0,Veronica Pestana,141.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
3,88 Seafood,4,1st time came was 5 months ago. A decent Cze C...,2023-10-29T10:48:53.638Z,0,Clo’s Laobu,68.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
4,88 Seafood,5,"First time experiencing prawning, we spend a g...",2023-08-08T05:02:23.357Z,0,Loh Soon Shan,120.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,Fu Zhen Seafood Restaurant,3,Affordable ZiChar stall located in a coffeesho...,2022-06-19T07:37:43.038Z,0,Bastian Lew,29.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10889,Fu Zhen Seafood Restaurant,4,"Beef hor fan thick gravy , savoury with beef s...",2022-05-23T04:59:31.966Z,1,Kelvin Teo,87.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10890,Fu Zhen Seafood Restaurant,4,"Ordered chicken fried rice with 2 extra eggs, ...",2021-09-28T09:52:23.269Z,0,Sihan Goi,247.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10891,Fu Zhen Seafood Restaurant,2,Not ordering from these guys again.\n\nGarlic ...,2022-09-19T11:36:43.707Z,0,Jeffrey “jf” Lim,78.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10892,Fu Zhen Seafood Restaurant,3,Egg was tasty but oysters not good,2022-10-27T12:24:29.650Z,0,MrHoopies,145.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en

In [5]:
# check how many languages are there for the reviews 
reviews.lang.unique()

array(['en', 'af', 'ro', 'cs', 'id', 'nl', 'so', 'fr', 'ja', 'zh-cn',
       'ko', 'NA', 'et', 'hr', 'no', 'sv', 'cy', 'es', 'tr', 'tl', 'de',
       'it', 'sl', 'fi', 'vi', 'da', 'pl', 'ca', 'sw'], dtype=object)

In [6]:
not_en = reviews.loc[reviews.lang != 'en']
not_en

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/41,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang
104,Thashan's curry,1,Very poor,2023-07-09T13:41:21.362Z,0,Sivan Sivanmoorthy,2.0,False,2023-08-07T07:54:52.917Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,af
105,Thashan's curry,5,Nice,2022-12-10T07:39:48.698Z,0,mani rk,94.0,False,2023-01-06T14:54:26.427Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ro
306,Gravy Bistro and Bar,5,Very nice,2023-10-31T06:53:41.111Z,0,Prajuri Deb Roy,1.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cs
469,HooHa Cafe,5,"Better than Katong Laksa, it’s as close to Per...",2021-01-30T12:56:45.397Z,2,Kit Fai Ho,18.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,id
839,Broadway Food Centre,5,Vegetarian very nice,2023-11-07T12:06:23.915Z,0,Rally Nismo 23,18.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10078,Srisun Prata,5,Pleasant encounter! Good Masala dosa at reason...,2023-05-07T04:12:39.478Z,0,Imon T.C,385.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,es
10691,Jade Chicken Rice Restaurant,5,Ho Jiak♥️♥️♥️,2020-12-28T10:17:55.772Z,0,Katherine Yap,8.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sw
10731,King Omar Restaurant,4,Wonderful breakfast prata.,2018-11-04T23:59:42.383Z,1,HK-me K,76.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ro
10881,Fu Zhen Seafood Restaurant,5,Always buy their Sambal Kang Kong.,2023-07-10T04:23:41.571Z,1,Desmond,453.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tl
10882,Fu Zhen Seafood Restaurant,4,Best,2024-01-09T13:40:51.379Z,0,HIN HOE CHEW,114.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de

In [7]:
# iterate thru the reviews flagged as not English and confirm not English
idxs = []
for i in not_en.index:
    idxs.append(i)

In [8]:
i = idxs[0]
print(f"index: {i}")
print(not_en['text'][i])

index: 104
Very poor

In [9]:
id_to_drop = [854, 871, 872, 1105, 1138, 1139, 1220, 1911, 1928, 1999, 2356, 2375, 2430, 3494, 3942, 5379, 5380, 7506, 9256, 9511, 9512, 10691]
print(f"number of reviews to drop: {len(id_to_drop)}")

number of reviews to drop: 22

In [10]:
reviews.drop(id_to_drop, axis=0, inplace=True)
reviews

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/41,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang
0,88 Seafood,4,"First time dinning here, tze char is just Infr...",2024-02-13T13:24:58.483Z,0,J Dotz,7.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
1,88 Seafood,5,This was my first time eating here. I can tell...,2023-12-25T02:14:33.909Z,0,judy ng,18.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
2,88 Seafood,4,Considering that the dining area is next to a ...,2024-01-09T15:06:22.201Z,0,Veronica Pestana,141.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
3,88 Seafood,4,1st time came was 5 months ago. A decent Cze C...,2023-10-29T10:48:53.638Z,0,Clo’s Laobu,68.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
4,88 Seafood,5,"First time experiencing prawning, we spend a g...",2023-08-08T05:02:23.357Z,0,Loh Soon Shan,120.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,Fu Zhen Seafood Restaurant,3,Affordable ZiChar stall located in a coffeesho...,2022-06-19T07:37:43.038Z,0,Bastian Lew,29.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10889,Fu Zhen Seafood Restaurant,4,"Beef hor fan thick gravy , savoury with beef s...",2022-05-23T04:59:31.966Z,1,Kelvin Teo,87.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10890,Fu Zhen Seafood Restaurant,4,"Ordered chicken fried rice with 2 extra eggs, ...",2021-09-28T09:52:23.269Z,0,Sihan Goi,247.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10891,Fu Zhen Seafood Restaurant,2,Not ordering from these guys again.\n\nGarlic ...,2022-09-19T11:36:43.707Z,0,Jeffrey “jf” Lim,78.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en
10892,Fu Zhen Seafood Restaurant,3,Egg was tasty but oysters not good,2022-10-27T12:24:29.650Z,0,MrHoopies,145.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en

In [11]:
reviews['num_words'] = reviews.text.str.split().str.len()
print(f"total number of words for all reviews: {reviews['num_words'].sum(axis=0)}")

total number of words for all reviews: 709618

In [12]:
print(f"total number of records/reviews: {reviews.shape[0]}")

total number of records/reviews: 10677

In [13]:
reviews.to_csv("cleaned_reviews.csv")

In [14]:
print(f"number of reviews to annotate for eval: {reviews.shape[0]*0.1}")

number of reviews to annotate for eval: 1067.7

In [15]:
to_annotate = reviews.sample(n=1068, replace=False)
to_annotate

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
7678,Iro Iro Japanese Restaurant,5,We were so excited to eat so the photos are ta...,2023-11-25T02:55:12.562Z,1,Lee Joleen,39.0,False,2023-12-10T15:15:19.003Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,338
5117,Pura Brasa Singapore,5,Really great Spanish food at reasonable prices...,2024-02-14T16:50:26.656Z,0,Randy Choo,26.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,40
3138,Sheik Jalani Restaurant,4,"Food range is amazing, food equality is slight...",2018-04-19T05:10:55.527Z,0,Miss Ain M,61.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,32
2683,Black Society 黑社会,5,Nice ambience - the room was well decorated wi...,2023-12-23T12:36:58.020Z,0,Marilyn Lau,2.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,46
620,BOMBAY DINING-NORTH INDIAN RESTAURANT,2,Ordered on Deliveroo and food arrived 50min la...,2021-05-22T11:13:00.211Z,4,Owen Lam,47.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6431,Melben Seafood Restaurant - Depot Lane,2,Purchased a mongolian style beef rice with egg...,2023-11-25T15:04:57.753Z,0,jinsen goh,48.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,26
2572,Tambi Restaurant,5,Oxtail Bone Marrow Murtabak 8/10 (Kimchi was a...,2024-02-21T13:37:15.730Z,0,Layla Said,37.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,57
9377,Ba Shu Sichuan Restaurant,5,Great tasting and authentic dishes here.\n\nWe...,2022-01-31T04:32:26.426Z,5,Jonneh Ng,8.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,58
9498,Mendon Bedok Mall,5,a small cozy nook beside Tori-Q that serves re...,2023-11-05T10:49:49.070Z,0,Xing Yi Han,5.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,90
7755,Hyderabad Bawarchi Authentic North Indian Rest...,5,Great place for Indian food.. affordable and n...,2023-08-02T11:46:53.103Z,0,lavanya veeraragavan,38.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,9

In [16]:
i = 178
ameeshi = to_annotate.iloc[0:i]
jacintha = to_annotate.iloc[i:i*2]
jewel = to_annotate.iloc[i*2:i*3]
junrong = to_annotate.iloc[i*3:i*4]
sherwin = to_annotate.iloc[i*4:i*5]
sreeja = to_annotate.iloc[i*5:i*6]

In [17]:
ameeshi

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
7678,Iro Iro Japanese Restaurant,5,We were so excited to eat so the photos are ta...,2023-11-25T02:55:12.562Z,1,Lee Joleen,39.0,False,2023-12-10T15:15:19.003Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,338
5117,Pura Brasa Singapore,5,Really great Spanish food at reasonable prices...,2024-02-14T16:50:26.656Z,0,Randy Choo,26.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,40
3138,Sheik Jalani Restaurant,4,"Food range is amazing, food equality is slight...",2018-04-19T05:10:55.527Z,0,Miss Ain M,61.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,32
2683,Black Society 黑社会,5,Nice ambience - the room was well decorated wi...,2023-12-23T12:36:58.020Z,0,Marilyn Lau,2.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,46
620,BOMBAY DINING-NORTH INDIAN RESTAURANT,2,Ordered on Deliveroo and food arrived 50min la...,2021-05-22T11:13:00.211Z,4,Owen Lam,47.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904,Don Dae Bak Restaurant,4,"The quality of the food we had, particularly t...",2023-07-02T15:10:42.152Z,0,VB Praline Noisette,60.0,True,2023-07-14T13:15:05.055Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,61
4967,Bochinche,5,"Argentinian Steakhouse, Charcoal Grilled Dry-A...",2023-12-30T04:58:14.639Z,0,Chew Chee Chin,73.0,True,2024-01-05T10:11:35.886Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,70
3874,Teppei Japanese Restaurant,4,Kaisendon options are good value and tasty. Th...,2023-08-27T04:57:20.102Z,0,Darren Yip,8.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,82
3143,Sheik Jalani Restaurant,5,My daughter is obsessed with their pratas. It ...,2021-05-30T12:38:44.093Z,0,Hanis Farina,16.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,23
4863,Nandhana's restaurant Eastpoint Simei,5,Visited a few times with my friends already. F...,2023-06-07T09:45:39.570Z,1,Rennie Lee,660.0,False,2023-06-08T09:51:57.855Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,25

In [18]:
jacintha

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
8889,Al Amaan Restaurant,5,Dropped by for dinner & there wasn’t a crowd w...,2020-11-07T08:54:47.785Z,1,Epompom,291.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,70
2173,Tempura Makino (Jewel Changi Airport),5,Our first time to try the food here.the food w...,2024-01-05T12:09:02.626Z,0,Jirathip Piam,8.0,False,2024-01-05T15:00:44.870Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,87
4172,Maji Curry Square 2,4,"The curry is nice, I like it better than Monst...",2024-03-01T11:40:43.990Z,0,Serene Fun,6.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,34
10203,Alati Divine Greek Cuisine,5,We had an absolutely divine birthday lunch. Ev...,2023-10-04T06:11:39.683Z,2,Pauline Yoong,519.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,18
6829,Ser Seng Herbs (Turtle) Restaurant,5,Our number 1 choice to go when introducing tur...,2022-12-25T02:01:26.204Z,0,Anna Chen,99.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9158,Swensen's @ West Mall,5,Was at Swensen's West Mall for dinner this eve...,2024-01-26T11:58:41.223Z,0,Irene new,2.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,64
8341,Chong Qing Grilled Fish Upper Thomson,5,We tried the Wanzhou Old School Grilled fish a...,2023-08-06T11:27:08.284Z,0,Kwong Fei Yee,434.0,False,2023-08-07T06:20:42.310Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,69
6053,SKIRT Restaurant,5,"Since they have new menu in Q3 2023, I finally...",2024-03-04T14:27:03.889Z,0,Siu ling Ng,1.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,29
302,Gravy Bistro and Bar,1,First and last time. The $13 bowl of fish (inc...,2023-09-13T05:26:27.991Z,2,Yes Ryan,9.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,39
9853,Black Pearl Steakhouse,5,"Ordered the dinner set, price was worth the po...",2023-07-07T14:34:01.361Z,1,Jer Lo,3.0,False,2023-07-08T10:41:11.554Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,73

In [19]:
jewel

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
4695,Stella Seaside Lounge,5,Need a car 🚗 to come to this place.\nWas here ...,2024-03-02T03:31:49.044Z,0,Boon Leong,273.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,47
10242,城记海鲜 Happy Chef Kitchen,5,Love the curry & nonya fish head. The prawn pa...,2024-02-26T03:16:06.739Z,0,chin khong danny toh,4.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,58
2267,Hokkaido Sushi,5,The food is nice and fresh. The yakimono and g...,2023-10-24T09:15:29.824Z,1,Surfire Du,13.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,25
10141,Gaig Singapore,5,"It was my first time at Restaurant Gaig, and I...",2023-06-02T11:26:57.523Z,2,Mighty Foodie,476.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,81
1111,Greenhouse Bistro,5,"The bistro is large and spacious, offering a d...",2023-08-26T12:59:24.098Z,2,Leslie Lee,149.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Pallet Cafe Bar,4,Staff were all very welcoming and attentive. M...,2024-02-25T10:24:13.350Z,0,CK C,1940.0,True,2024-02-25T10:36:22.713Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,61
8602,PocoLoco,3,Very overrated…. The carbonara portion was sma...,2024-02-10T12:47:34.936Z,0,Eric Lee,633.0,False,2024-01-10T09:58:45.367Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,35
9311,Hock Seng Choon Fishball Kway Teow Mee (#01-50),3,Repeat or Not…Not. The queue was quite long ar...,2022-09-04T13:33:08.542Z,0,Jonathan Ng,65.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,67
237,Rasa Istimewa Waterfront Restaurant,3,"The restaurant offers scenic views, situated a...",2022-03-21T21:54:21.414Z,8,Dr Reviews,439.0,True,NaN,NaN,...,https://lh5.googleusercontent.com/p/AF1QipOkNF...,https://lh5.googleusercontent.com/p/AF1QipO3Gu...,https://lh5.googleusercontent.com/p/AF1QipMMm5...,https://lh5.googleusercontent.com/p/AF1QipPKsy...,https://lh5.googleusercontent.com/p/AF1QipPZke...,https://lh5.googleusercontent.com/p/AF1QipNPyQ...,https://lh5.googleusercontent.com/p/AF1QipOqcr...,https://lh5.googleusercontent.com/p/AF1QipPRzM...,en,135
8976,81 Restaurant,5,Atmosphere is great and food were nice. Especi...,2021-03-17T00:34:00.551Z,2,Fung峰,55.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,22

In [20]:
junrong

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
10445,Long Beach UDMC,5,I had a fantastic experience at this restauran...,2023-06-22T06:56:34.872Z,0,Daniel Wu,8.0,False,2023-07-05T06:02:47.874Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,88
57,Canopy HortPark,5,"had an amazing experience there, with service ...",2024-02-24T04:53:01.401Z,0,madhu lika,6.0,False,2024-02-28T02:24:10.680Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,48
9587,Satay Solo,1,The uncle serving the satay here was EXTREMELY...,2024-02-23T09:34:15.209Z,0,Siti Mahmudah,3.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,41
9502,Mendon Bedok Mall,2,The food is different from what picture looks ...,2022-09-22T12:44:44.330Z,1,Ada HUANG,35.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,30
7051,Good Bites,5,We got a voucher after dining in at Galangal B...,2023-11-18T12:54:19.655Z,0,Joanna Lee,74.0,False,2023-11-22T01:37:13.791Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6709,Soup Restaurant @ Holland Village,4,Good comfort food in a central convenient loca...,2021-01-26T15:50:23.332Z,0,Lily T,462.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,20
2838,No Menu Restaurant,5,Food was really great here service was amazing...,2023-08-22T15:00:23.262Z,0,Zatarie Hoe,295.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,77
4596,GO Noodle House Changi Airport T2,5,The winning dish is the suan cai broth! Spicy ...,2023-04-16T13:12:12.568Z,0,Yihan Lin,187.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,89
7296,Pham Quyen Vietnamese Cuisine @ Pasir Panjang Rd,5,We really miss Vietnam so we came for Bahn Mi ...,2023-09-26T01:23:16.685Z,1,Ash Ash,33.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,90
2563,Tambi Restaurant,3,Mains were uninspiring — tasted like elevated ...,2024-01-07T16:48:52.393Z,2,Jay Lee,16.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,66

In [21]:
sherwin

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
5519,Wrap City - North Indian Vegetarian Restaurant,4,India authentic vegitarian wraps and biryani c...,2022-12-16T10:13:58.709Z,1,Kenny Cheong,104.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,14
8789,Dario Pizza & More,5,Wow! This is so tasty. It's authentic and the ...,2023-12-05T15:20:43.184Z,0,raspberrih,15.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,35
6557,Ayza’s Restaurant,1,Super overpriced naan… 2 naan and small portio...,2024-01-08T12:30:12.699Z,1,MuscleCameraMan Ong,3.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,15
4251,Nara,3,This place serve decent Japanese food but the ...,2020-03-05T06:25:30.240Z,0,Mark Ong,659.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,88
1971,Hawa Restaurant,5,This restaurant brings back memories of our ch...,2022-10-15T03:46:22.842Z,2,Stepheb Chung,11.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8476,Hong Sheng Restaurant - Claypot Fish Head,2,Honestly a lousy meal. The so called claypo...,2023-09-23T09:54:02.800Z,1,Frank Tan,116.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,53
1612,Sushiro Jewel Changi,5,Affordable and delicious sushi! Every rice is ...,2023-09-16T12:12:55.322Z,0,Faith,290.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,83
585,Poulet - Causeway Point,5,Nice french restaurant. Service workers very n...,2023-11-16T12:51:29.397Z,0,Muhammad Amirruddin Abdullah,7.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,35
546,Al-Ameen Eating Corner,5,Quite a nice supper spot. Halal eatery! Has fo...,2023-05-12T17:01:23.993Z,1,Terence Ho Yan King,76.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,77
5879,Al Hadheerah Restaurant (HDB Hub),5,Al Hadheerah is located at the basement foodco...,2020-11-21T03:12:57.599Z,1,Jack Sheo,63.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,54

In [22]:
sreeja

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/42,reviewImageUrls/43,reviewImageUrls/44,reviewImageUrls/45,reviewImageUrls/46,reviewImageUrls/47,reviewImageUrls/48,reviewImageUrls/49,lang,num_words
5192,Sona's Grill Restaurant,4,Food is generally good. Serving size on the sm...,2023-06-24T11:55:23.125Z,0,lp Leong,58.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,95
2102,Sakura Family Restaurant,2,My friend and I are post duty from work and de...,2023-10-13T10:50:49.319Z,1,Ivy Abella,78.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,116
7344,Jai Thai Restaurant,4,Their food is tasty and affordable. We ordered...,2023-02-17T17:19:32.971Z,2,wendy khng,198.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,117
4710,Tapas Club,4,A Mixed Experience at Tapas Club: Delectable C...,2023-11-07T04:46:20.691Z,2,Joe Yap,45.0,True,2023-11-28T03:16:56.757Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,150
2395,Family Flavor Restaurant,4,Average taste with affordable price. Overall g...,2023-03-03T12:26:11.243Z,2,Terry Ding,390.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6431,Melben Seafood Restaurant - Depot Lane,2,Purchased a mongolian style beef rice with egg...,2023-11-25T15:04:57.753Z,0,jinsen goh,48.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,26
2572,Tambi Restaurant,5,Oxtail Bone Marrow Murtabak 8/10 (Kimchi was a...,2024-02-21T13:37:15.730Z,0,Layla Said,37.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,57
9377,Ba Shu Sichuan Restaurant,5,Great tasting and authentic dishes here.\n\nWe...,2022-01-31T04:32:26.426Z,5,Jonneh Ng,8.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,58
9498,Mendon Bedok Mall,5,a small cozy nook beside Tori-Q that serves re...,2023-11-05T10:49:49.070Z,0,Xing Yi Han,5.0,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,90
7755,Hyderabad Bawarchi Authentic North Indian Rest...,5,Great place for Indian food.. affordable and n...,2023-08-02T11:46:53.103Z,0,lavanya veeraragavan,38.0,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en,9

In [23]:
to_annotate.to_csv("to_annotate.csv")

In [24]:
ameeshi[['text']].to_csv("ameeshi.csv")
jacintha[['text']].to_csv("jacintha.csv")
jewel[['text']].to_csv("jewel.csv")
junrong[['text']].to_csv("junrong.csv")
sherwin[['text']].to_csv("sherwin.csv")
sreeja[['text']].to_csv("sreeja.csv")

In [25]:
ameeshi.to_csv("ameeshi_orig.csv")
jacintha.to_csv("jacintha_orig.csv")
jewel.to_csv("jewel_orig.csv")
junrong.to_csv("junrong_orig.csv")
sherwin.to_csv("sherwin_orig.csv")
sreeja.to_csv("sreeja_orig.csv")